/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractsUpgradeableDiamond from "./contracts-upgradeable-diamond";
export type { contractsUpgradeableDiamond };
