# Cloudflare Pages configuration for GNUS DAO
name = "gnus-dao-governance"
compatibility_date = "2024-01-01"

[env.production]
# Production environment configuration
vars = {
  NODE_ENV = "production",
  STATIC_EXPORT = "true",
  NEXT_PUBLIC_SEPOLIA_GNUS_DAO_ADDRESS = "0x4d638F3c61F7B8BBa4461f80a4aa7315795812EF"
}

[env.preview]
# Preview environment configuration
vars = { NODE_ENV = "development" }

# Pages configuration
[pages]
pages_build_output_dir = "out"
build_command = "yarn build"
# Custom domains (configure in Cloudflare dashboard)
# custom_domains = ["dao.gnus.ai"]

# Environment variables (set in Cloudflare dashboard)
# These should be configured in the Cloudflare Pages dashboard:
# - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
# - NEXT_PUBLIC_ETHEREUM_RPC_URL
# - NEXT_PUBLIC_BASE_RPC_URL
# - NEXT_PUBLIC_POLYGON_RPC_URL
# - NEXT_PUBLIC_SKALE_RPC_URL
# - NEXT_PUBLIC_SEPOLIA_GNUS_DAO_ADDRESS (for testnet)

# Security headers are configured in public/_headers file
