# Cloudflare Pages configuration for GNUS DAO
name = "gnus-dao-governance"
compatibility_date = "2024-01-01"

[env.production]
# Production environment configuration
vars = { NODE_ENV = "production" }

[env.preview]
# Preview environment configuration  
vars = { NODE_ENV = "development" }

# Build configuration
[build]
command = "yarn build:cloudflare"
destination = "out"

# Pages configuration
[pages]
# Custom domains (configure in Cloudflare dashboard)
# custom_domains = ["dao.gnus.ai"]

# Environment variables (set in Cloudflare dashboard)
# These should be configured in the Cloudflare Pages dashboard:
# - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
# - NEXT_PUBLIC_ETHEREUM_RPC_URL
# - NEXT_PUBLIC_BASE_RPC_URL
# - NEXT_PUBLIC_POLYGON_RPC_URL
# - NEXT_PUBLIC_SKALE_RPC_URL
# - NEXT_PUBLIC_SEPOLIA_GNUS_DAO_ADDRESS (for testnet)

# Security headers are configured in public/_headers file
