/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  GNUSDAOValueFacet,
  GNUSDAOValueFacetInterface,
} from "../../../contracts/gnus-dao/GNUSDAOValueFacet";

const _abi = [
  {
    inputs: [],
    name: "getMaxSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getNumericValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenSymbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610234806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c8063862b092b11610050578063862b092b146100cd578063d13d906614610106578063f1850af81461010d57600080fd5b8063209652551461006c5780634c0f38c2146100b7575b600080fd5b60408051808201909152601f81527f48656c6c6f2066726f6d20474e555344414f2056616c7565204661636574210060208201525b6040516100ae9190610163565b60405180910390f35b6100bf610146565b6040519081526020016100ae565b60408051808201909152600e81527f474e555344414f20546f6b656e7300000000000000000000000000000000000060208201526100a1565b602a6100bf565b60408051808201909152600481527f4744414f0000000000000000000000000000000000000000000000000000000060208201526100a1565b600061015e670de0b6b3a76400006302faf0806101b8565b905090565b600060208083528351808285015260005b8181101561019057858101830151858201604001528201610174565b818111156101a2576000604083870101525b50601f01601f1916929092016040019392505050565b60008160001904831182151516156101f9577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b50029056fea2646970667358221220e6bbaa7d12b38da59203d5dbd25ec122aacb33c72898ed94296b6d0b16151d5c64736f6c63430008090033";

type GNUSDAOValueFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GNUSDAOValueFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GNUSDAOValueFacet__factory extends ContractFactory {
  constructor(...args: GNUSDAOValueFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GNUSDAOValueFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GNUSDAOValueFacet__factory {
    return super.connect(runner) as GNUSDAOValueFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GNUSDAOValueFacetInterface {
    return new Interface(_abi) as GNUSDAOValueFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GNUSDAOValueFacet {
    return new Contract(address, _abi, runner) as unknown as GNUSDAOValueFacet;
  }
}
