/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC165StorageUpgradeable,
  ERC165StorageUpgradeableInterface,
} from "../../../../../@gnus.ai/contracts-upgradeable-diamond/utils/introspection/ERC165StorageUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC165StorageUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ERC165StorageUpgradeableInterface {
    return new Interface(_abi) as ERC165StorageUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC165StorageUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ERC165StorageUpgradeable;
  }
}
